In [ ]:
import time
import numpy as np

In [ ]:
x = np.random.random(100000000)

In [37]:
start = time.time()
sum(x)/len(x) 
print(time.time()-start)
start = time.time()
y=np.mean(x) # compare how fast is using numpy
# print(y)
print(time.time()-start)


9.42636227607727
0.06912899017333984


In [31]:
seconds_since_1970=time.time()
minutes= seconds_since_1970/60
hours = minutes/60
days = hours/24
years =  days/365.25

print(f"The total year since 1970 is {int(years)}")

The total year since 1970 is 53


In [38]:
nd_arr = np.array([1,2,3,4,5,6,7])
print(nd_arr)
print(type(x))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [43]:
nd_arr.dtype

dtype('int64')

In [44]:
nd_arr.shape

(7,)

In [53]:
nd_arr = np.array([[1,3,5,7,9],[3,2,7,6,9],[6,8,7,9,2]])

In [54]:
nd_arr.shape

(3, 5)

In [55]:
nd_arr.size

15

In [56]:
x = np.array(['Hello', 'World'])

## We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


In [57]:
x = np.array([1, 2, 'World'])

## We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


In [58]:
## We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

## We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

## We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

## We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


In [60]:
# '''We can see that when we create an ndarray with only floats, 
# NumPy stores the elements in memory as 64-bit floating point numbers
# (float64). However, notice that when we create an ndarray with both floats 
# and integers, as we did with the z ndarray above, NumPy assigns its
# elements a float64 dtype as well. This is called upcasting. Since all
# the elements of an ndarray must be of the same type, in this case
# NumPy upcasts the integers in z to floats in order to avoid losing 
# precision in numerical computations.'''

In [61]:
## We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

## We print the dtype x
print('x = ', x)
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
The elements in x are of type: int64


In [62]:
## We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

print('Y = \n', Y)

## We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [63]:
## We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

## We save x into the current directory as 
np.save('my_array', x)

In [64]:
## We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

## We print y
print()
print('y = ', y)
print()

## We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int64
